const express = require('express');
const authRoutes = require('./authRoutes');
const userRoutes = require('./userRoutes');
const profileRoutes = require('./profileRoutes');
const connectionRoutes = require('./connectionRoutes');
const postRoutes = require('./postRoutes');
const notificationRoutes = require('./notificationRoutes');
const fileRoutes = require('./fileRoutes');
const settingsRoutes = require('./settingsRoutes');
const adminRoutes = require('./adminRoutes');
const supportRoutes = require('./supportRoutes');
const verificationRoutes = require('./verificationRoutes');
const webhookRoutes = require('./webhookRoutes');
const legalRoutes = require('./legalRoutes');
const paymentRoutes = require('./paymentRoutes');
const jobRoutes = require('./jobRoutes');
const applicationRoutes = require('./applicationRoutes');
const interviewRoutes = require('./interviewRoutes');
const analyticsRoutes = require('./analyticsRoutes');
const scorecardRoutes = require('./scorecardRoutes');
const conversationRoutes = require('./conversationRoutes');
const networkingRoutes = require('./networkingRoutes');
const liveRoutes = require('./liveRoutes');
const { idempotencyMiddleware } = require('../middleware/idempotency');

const router = express.Router();

router.use(idempotencyMiddleware);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/profiles', profileRoutes);
router.use('/connections', connectionRoutes);
router.use('/posts', postRoutes);
router.use('/notifications', notificationRoutes);
router.use('/files', fileRoutes);
router.use('/settings', settingsRoutes);
router.use('/admin', adminRoutes);
router.use('/support', supportRoutes);
router.use('/verification', verificationRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/legal', legalRoutes);
router.use('/', paymentRoutes);
router.use('/jobs', jobRoutes);
router.use('/applications', applicationRoutes);
router.use('/interviews', interviewRoutes);
router.use('/scorecards', scorecardRoutes);
router.use('/', analyticsRoutes);
router.use('/', conversationRoutes);
router.use('/networking', networkingRoutes);
router.use('/live', liveRoutes);

module.exports = router;
