const express = require('express');
const authRoutes = require('./authRoutes');
const userRoutes = require('./userRoutes');
const profileRoutes = require('./profileRoutes');
const connectionRoutes = require('./connectionRoutes');
const postRoutes = require('./postRoutes');
const notificationRoutes = require('./notificationRoutes');
const fileRoutes = require('./fileRoutes');
const settingsRoutes = require('./settingsRoutes');
const adminRoutes = require('./adminRoutes');
const supportRoutes = require('./supportRoutes');
const verificationRoutes = require('./verificationRoutes');
const webhookRoutes = require('./webhookRoutes');
const legalRoutes = require('./legalRoutes');
const searchRoutes = require('./searchRoutes');
const organizationRoutes = require('./organizationRoutes');
const projectRoutes = require('./projectRoutes');
const gigRoutes = require('./gigRoutes');
const jobRoutes = require('./jobRoutes');
const groupRoutes = require('./groupRoutes');
const { idempotencyMiddleware } = require('../middleware/idempotency');

const router = express.Router();

router.use(idempotencyMiddleware);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/profiles', profileRoutes);
router.use('/connections', connectionRoutes);
router.use('/posts', postRoutes);
router.use('/notifications', notificationRoutes);
router.use('/files', fileRoutes);
router.use('/settings', settingsRoutes);
router.use('/admin', adminRoutes);
router.use('/support', supportRoutes);
router.use('/verification', verificationRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/legal', legalRoutes);
router.use('/search', searchRoutes);
router.use('/organizations', organizationRoutes);
router.use('/projects', projectRoutes);
router.use('/gigs', gigRoutes);
router.use('/jobs', jobRoutes);
router.use('/groups', groupRoutes);

module.exports = router;
